CREATE TABLE IF NOT EXISTS public.user_preferences (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE,
  job_status text,
  expected_salary numeric,
  roles jsonb DEFAULT '[]'::jsonb,
  role_values jsonb DEFAULT '[]'::jsonb,
  locations jsonb DEFAULT '[]'::jsonb,
  work_modes jsonb DEFAULT '[]'::jsonb,
  company_sizes jsonb DEFAULT '[]'::jsonb,
  industries_prefer jsonb DEFAULT '[]'::jsonb,
  industries_avoid jsonb DEFAULT '[]'::jsonb,
  skills_prefer jsonb DEFAULT '[]'::jsonb,
  skills_avoid jsonb DEFAULT '[]'::jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);


ALTER TABLE public.user_preferences ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can read own preferences"
  ON public.user_preferences FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own preferences"
  ON public.user_preferences FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own preferences"
  ON public.user_preferences FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

COMMENT ON TABLE public.user_preferences IS 'Job preferences per user';
