-- User personal info for Autofill Agent: name, contact, work history, education, etc.
-- Run in Supabase SQL Editor or via: supabase db push

CREATE TABLE IF NOT EXISTS public.user_personal_info (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE,
  first_name text,
  last_name text,
  email text,
  phone text,
  location text,
  linkedin_url text,
  education_summary text,
  work_history_summary text,
  expected_salary text,
  availability text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_user_personal_info_user_id ON public.user_personal_info(user_id);

ALTER TABLE public.user_personal_info ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own personal info"
  ON public.user_personal_info FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own personal info"
  ON public.user_personal_info FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own personal info"
  ON public.user_personal_info FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

COMMENT ON TABLE public.user_personal_info IS 'Stored profile for Autofill Agent and tailored answers';
